# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Format code
      run: flutter format --set-exit-if-changed .

    - name: Analyze code
      run: flutter analyze --fatal-infos

    - name: Run tests
      run: flutter test

    - name: Publish
      uses: k-paxian/dart-package-publisher@v1.5
      with:
        credentialJson: ${{ secrets.CREDENTIAL_JSON }}
        flutter: true
        skipTests: true
